### ISSUE TITLE
Version 1.0 TODO

### ISSUE THREAD

**Issue by nswa17** [taulukointipalvelut/utab-core-js#1]
- [x] データチェック
- [x] finishing_process
- [x] conflicts
- [x] delete results
- [x] institution と team 分離, t => insti, a => insti のデータベース作成
- [x] set current num
- [x] average and sd, ranking of debater scores
- [x] res, db統合
- [x] adjudicatorallocationを後から作る場合
- [x] update resultsはrawのみ
- [x] ソースtool分割
- [x] availableのみでmatching
- [x] get_element_by_id を消すtosearch
- [x] schema にuid付加
- [x] databaseコネクションインスタンス
- [x] 動的なラウンド数の変更
- [x] database.jsの関数の返値はpromise
- [x] resultsの扱い
- [x] debaterのaverageの出し方
- [x] get team allocation from matching改善
- [x] _to_はキーが存在しない場合[]を返す.
- [x] update team to debaters already existsのerrorhandle

**Comment by nswa17** [comment]
- [ ] conflicts

**Comment by nswa17** [comment]
非同期化
- [ ] core.js
- [ ] operations.js
    - [ ] adjfilters.js
    - [ ] filters.js
    - [ ] sys.js
- [ ] controller2.js
- [ ] database.js
